### ISSUE TITLE
Version 0.6.3 pypi package is broken

### ISSUE THREAD

**Issue by Geethree** [ContinuumIO/pycosat#31]
It is missing the `README.rst`
```shell
ubuntu@ip-172-31-43-135:~$ sudo pip3 install pycosat
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pycosat
  Downloading pycosat-0.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-idnz7zr3/pycosat/setup.py", line 51, in <module>
        long_description = open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

The tar available via pypi [pycosat-0.6.3.tar.gz](https://pypi.python.org/packages/38/4f/1bc5f58ffae88264c7d4de265a2ec742715de3094a83d3f2ae7f95d91d19/pycosat-0.6.3.tar.gz#md5=e4ed514dcb38e04a7697b812ba5c3515) is indeed missing the `README.rst`:
```shell
ubuntu@ip-172-31-43-135:~$ wget https://pypi.python.org/packages/38/4f/1bc5f58ffae88264c7d4de265a2ec742715de3094a83d3f2ae7f95d91d19/pycosat-0.6.3.tar.gz#md5=e4ed514dcb38e04a7697b812ba5c3515
--2017-11-08 19:59:52--  https://pypi.python.org/packages/38/4f/1bc5f58ffae88264c7d4de265a2ec742715de3094a83d3f2ae7f95d91d19/pycosat-0.6.3.tar.gz
Resolving pypi.python.org (pypi.python.org)... 151.101.52.223, 2a04:4e42:d::223
Connecting to pypi.python.org (pypi.python.org)|151.101.52.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7957 (7.8K) [binary/octet-stream]
Saving to: ‘pycosat-0.6.3.tar.gz’

pycosat-0.6.3.tar.gz          100%[================================================>]   7.77K  --.-KB/s    in 0s      

2017-11-08 19:59:52 (150 MB/s) - ‘pycosat-0.6.3.tar.gz’ saved [7957/7957]

ubuntu@ip-172-31-43-135:~$ tar -xvzf pycosat-0.6.3.tar.gz 
pycosat-0.6.3/
pycosat-0.6.3/PKG-INFO
pycosat-0.6.3/pycosat.c
pycosat-0.6.3/setup.py
pycosat-0.6.3/test_pycosat.py
```
The 0.6.3 tar on github is not missing this file.

**Comment by csoja** [comment]
Should be fixed now in the version @ilanschnell uploaded on 2017-11-09.  Thank you @Geethree for reporting the issue!
